export const navLinksdata = [
  {
    _id: 1001,
    title: "HOME",
    link: "/",
  },
  {
    _id: 1002,
    title: "COURSES",
    link: "/courses",
  },
  {
    _id: 1003,
    title: "GRANTS",
    link: "/grants",
  },
];
export const researchData2023 = [
  {
    _id: 2001,
    data: "1. Tripathi, N., N. Bhardwaj, S. Kumar and S. K. Jain A machine learning-based KNIME workflow to predict VEGFR-2 inhibitors.' Chemical Biology & Drug Design https://doi.org/10.1111/cbdd.14250.",
  },
  {
    _id: 2002,
    data: "2. Singh, V., K. S. Jain and V. Mishra (2023). 'A Recent Update on SARS-CoV-2 Transmission and its Variants: Transmission, Pathogenic Mechanism, and Treatment.' Coronaviruses 4(1): 3-15. DOI: 10.2174/2666796704666230102121225",
  },
  {
    _id: 2003,
    data: "3. Kumar, S., N. Singh, A. Mittal, H. Kharkwal, S. K. Jain and B. Goel (2023). 'The genus Leucas: A review on phytochemistry and pharmacological activities. Fitoterapia 167: 105492.' https://doi.org/10.1016/j.fitote.2023.105492 .",
  },
];
export const researchData2022 = [
  {
    _id: 2004,
    data: "1. Goel, B.; Reddy, H.; Cholkar, A.; Kumar, S.; Guru, S. K.; Jain, S.K. Isolation of a new cytotoxic colchinoid from Gloriosa superba roots. Natural Product Research 2022, DOI:10.1080/14786419.2022.2158464",
  },
  {
    _id: 2005,
    data: "2. Goel, B.; Jain, S. K. Natural products as a source of cytotoxic warheads in antibody-drug conjugates. Natural Product Research 2022, DOI:10.1080/14786419.2022.2138872",
  },
  {
    _id: 2006,
    data: "3. Goel, B.; Dey, B.; Chatterjee, E.; Tripathi, N.; Bhardwaj, N.; Kumar, S.; Guru, S. K.; Jain, S. K., Antiproliferative Potential of Gloriosine: A Lead for Anticancer Drug Development. ACS Omega 2022. https://doi.org/10.1021/acsomega.2c02688 (IF:4.132)",
  },
  {
    _id: 2007,
    data: "4. Kushwaha, M.; Qayum, A.; Sharma, N.; Abrol, V.; Choudhary, P.; Murtaza, M.; Singh, S. K.; Vishwakarma, R. A.; Goutam, U.; Jain, S.K.; Jaglan, S., LC–PDA–MS/MS-Based Dereplication Guided Isolation of a New Optical Isomer of 19,20-Epoxycytochalasin-N and Its Cytotoxic Activity. ACS Omega 2022. https://doi.org/10.1021/acsomega.2c03037(Co-corresponding, IF:4.132)",
  },
  {
    _id: 2008,
    data: "5. Tripathi, N.; Goel, B.; Bhardwaj, N.; Vishwakarma, R. A.; Jain, S.K., Exploring the Potential of Chemical Inhibitors for Targeting Post-translational Glycosylation of Coronavirus (SARS-CoV-2). ACS Omega 2022. https://doi.org/10.1021/acsomega.2c02345 (corresponding, INVITED REVIEW) IF: 4.132",
  },
  {
    _id: 2009,
    data: "6. Shreya, S.; Jain, S. K.; Guru, K. S.; Sahu, N. A., Anti-cancer potential of Pleurotus mushroom: Detailed insight on the potential bioactive molecules, Invitro-Invivo studies, and formulation. Letters in Drug Design & Discovery, 2022. 19: p. 1-1. DOI: 10.2174/1570180819666220518100010 (IF 1.02)",
  },
  {
    _id: 2010,
    data: "7. Ramakrishna, K., S.K. Jain, and S. Krishnamurthy, Pharmacokinetic and Pharmacodynamic Properties of Indole-3-carbinol in Experimental Focal Ischemic Injury. European Journal of Drug Metabolism and Pharmacokinetics, 2022. 47(4): p. 593-605. https://doi.org/10.1007/s13318-022-00771-y (IF 2.46)",
  },
  {
    _id: 2011,
    data: "8. Jayesh Tiwari, Nancy Tripathi, Ravi Shanker Srivastava, Sujeet Kumar, Sanjay Singh, Shreyans Jain, Arun Khattri, Low expression of TMPRSS2–a SARS-CoV-2 internalization protease–associates with basal subtype of head and neck squamous cell carcinoma, Translational Oncology, 22, 2022, 101458, https://doi.org/10.1016/j.tranon.2022.101458. (IF 4.243)",
  },
  {
    _id: 2012,
    data: "9. Goel B, Tiwari AK, Pandey RK, Singh AP, Kumar S, Sinha A, Jain SK, Khattri A. 2022. Therapeutic approaches for the treatment of head and neck squamous cell carcinoma–An update on clinical trials. Translational Oncology. 2022/07/01/;21:101426. https://doi.org/10.1016/j.tranon.2022.101426 (IF 4.243)",
  },
  {
    _id: 2013,
    data: "10. Goel B, Tripathi N, Bhardwaj N, Kumar A, Jain SK. 2022. Iodine-mediated one-step synthesis of ipomone from gibberellic acid. Natural Product Research.1-8. https://doi.org/10.1080/14786419.2022.2065487 (IF 2.861)",
  },
  {
    _id: 2014,
    data: "11. Nalli, Y. K., S. K. Guru, P. Jain, V. Mishra and S. K. Jain(2022). 'Bioassay-Guided Fractionation and Dereplication Studies of Sesame oil: Isolation of 8-Acetoxypinoresinol as an Anti-Proliferative Metabolite and Prediction of Target.' Proceedings of the National Academy of Sciences, India Section B: Biological Sciences. https://doi.org/10.1007/s40011-021-01308-0 (IF: 0.96)",
  },
  {
    _id: 2015,
    data: "12. Prasad J, Das S, Maurya A, Jain SK, Dwivedy AK. (2022) Synthesis, characterization and in situ bioefficacy evaluation of Cymbopogon nardus essential oil impregnated chitosan nanoemulsion against fungal infestation and aflatoxin B1 contamination in food system. International Journal of Biological Macromolecules. https://doi.org/10.1016/j.ijbiomac.2022.02.060 (IF 6.953)",
  },
  {
    _id: 2016,
    data: "13. Sahu, B., N. Bhardwaj, E. Chatterjee, B. Dey, N. Tripathi, B.Goel, M. Kushwaha, B. Kumar, B. Singh, S. K. Guru and S. K. Jain (2022). 'LCMS-DNP based dereplication of Araucaria cunninghamii Mudie gum-resin: identification of new cytotoxic labdane diterpene.' Natural Product Research: 1-8. https://doi.org/10.1080/14786419.2021.2024530(IF 2.861)",
  },
];
export const researchData2021 = [
  {
    _id: 3001,
    data: "1. Rajagopal, M. U., S. Bansal, P. Kaur, S. K. Jain, T. Altadil, C. P. Hinzman, Y. Li, J. Moulton, B. Singh, S. Bansal, S. K. Chauthe, R. Singh, P. P. Banerjee, M. Mapstone, M. S. Fiandaca, H. J. Federoff, K. Unger, J. P. Smith and A. K. Cheema (2021). 'TGF&beta; Drives Metabolic Perturbations during Epithelial Mesenchymal Transition in Pancreatic Cancer: TGF&beta; Induced EMT in PDAC.' Cancers 13(24). https://doi.org/10.3390/cancers13246204 (IF 6.639)",
  },
  {
    _id: 3002,
    data: "2. Bhardwaj N, Goel B, Tripathi N, Sahu B, Jain SK. 2021. A Comprehensive Review on Chemistry and Pharmacology of Marine Bioactives as Antimetastatic Agents. European Journal of Medicinal Chemistry Reports. 2021/12/07/:100023.",
  },
  {
    _id: 3003,
    data: "3. Manhas D, Gour A, Bhardwaj N, Sharma DK, Sharma K, Vij B, Jain SK, Singh G, Nandi U. 2021. Pharmacokinetic Assessment of Rottlerin from Mallotus philippensis Using a Highly Sensitive Liquid Chromatography–Tandem Mass Spectrometry-Based Bioanalytical Method. ACS Omega. 2021/12/07;6:32637-32646. (IF 3.512)",
  },
  {
    _id: 3004,
    data: "4. N. Bhardwaj, A. K. Singh, N. Tripathi, B. Goel, A. Indra and Shreyans K. Jain. 'Ni-NiO Heterojunction: A Versatile Nanocatalyst for the Regioselective Halogenation and Oxidative Esterification of Aromatics. New Journal of Chemistry.' 2021 Accepted: https://doi.org/10.1039/D1NJ02777H (IF 3.288)",
  },
  {
    _id: 3005,
    data: "5. Bharat Goel, Essha Chatterjee, Biswajit Dey, Nancy Tripathi, Nivedita Bhardwaj, Arun Khattri, Santosh Kumar Guru, and Shreyans K. Jain 'Identification and Evaluation of Apoptosis-Inducing Activity of Ipomone from Ipomoea nil: A Novel, Unusual Bicyclo-[3.2.1] Octanone Containing Gibberic Acid Diterpenoid.'ACS Omega 2021, 6, 12, 8253–8260 https://doi.org/10.1021/acsomega.0c06304) (IF 3.512)",
  },
  {
    _id: 3006,
    data: "6. Manoj Kushwaha, Arem Qayum, Shreyans K. Jain, Jasvinder singh, Amit Srivastava, Shubham Srivastava, Nisha Sharma, Vidushi Abrol, Ruchi Malik, Shashank Singh, Ram A. Vishwakarma, Sandeep  Jaglan, 'The Tandem MS-based metabolite profiling of 19,20-epoxycytochalasin C, reveals the importance of hydroxy group at the C-7 position for biological activity' ACS Omega 2021, 6, 5, 3717–3726, https://doi.org/10.1021/acsomega.0c05307) (IF 3.512)",
  },
  {
    _id: 3007,
    data: "7. Bharat Goel, Nancy Tripathi, Debaraj Mukherjee & Shreyans K. Jain*, Glycorandomization: A promising diversification strategy for the drug development. European Journal of Medicinal Chemistry, 2021: 213, 113156 https://doi.org/10.1016/j.ejmech.2021.113156) (I.F- 5.572)",
  },
  {
    _id: 3008,
    data: "8. Nivedita Bhardwaj, Nancy Tripathi, Bharat Goel & Shreyans K. Jain*, Anticancer Activity of Diosgenin and its Semi-synthetic Derivatives: Role in Autophagy Mediated Cell Death and Induction of Apoptosis. Mini-Reviews in Medicinal Chemistry, 2020. (Accepted, https://doi.org/10.2174/1389557521666210105111224) (I.F-2.73)",
  },
];
export const researchData2020 = [
  {
    _id: 4001,
    data: "1. Bharat Goel, Nivedita Bhardwaj, Nancy Tripathi, & Shreyans K. Jain*, Drug discovery of small molecules for the treatment of COVID-19: A review on clinical studies. Mini-Reviews in Medicinal Chemistry, 2020. (doi: https://doi.org/10.2174/1389557521666201228145755) (I.F-2.73)",
  },
  {
    _id: 4002,
    data: "2. Nancy Tripathi, Bharat Goel, Nivedita Bhardwaj, Bharat Sahu, Hemant Kumar, & Shreyans K. Jain*, Virtual screening and molecular simulation study of natural products database for lead identification of novel coronavirus main protease inhibitors. Journal of Biomolecular Structure and Dynamics, 2020: 1-13. (doi: https://doi.org/10.1080/07391102.2020.1848630) (I.F-3.310)",
  },
  {
    _id: 4003,
    data: "3. Bharat Goel, Ved Vyas, Nancy Tripathi, Ajit Kumar Singh, Prashanth W. Menezes, Arindam Indra, & Shreyans K. Jain*, Amidation of Aldehydes with Amines under Mild Conditions Using Metal-Organic Framework Derived NiO@Ni Mott-Schottky Catalyst. ChemCatChem, 12, 2020: 5743-5749. (doi: https://doi.org/10.1002/cctc.202001041) (I.F-4.853)",
  },
  {
    _id: 4004,
    data: "4. Bharat Goel, Nancy Tripathi, Nivedita Bhardwaj, Bharat Sahu, & Shreyans K. Jain*, Therapeutic potential of genus Pongamia and Derris: Phytochemical and bioactivity. Mini-Reviews in Medicinal Chemistry, 2020. (doi: https://doi.org/10.2174/1389557520999201124211846) (I.F-2.73)",
  },
  {
    _id: 4005,
    data: "5. Bharat Goel, Nancy Tripathi, Nivedita Bhardwaj, & Shreyans K. Jain*, Small Molecule CDK Inhibitors for the Therapeutic Management of Cancer. Current Topics in Medicinal Chemistry, 20, 2020: 1535-1563. (doi: https://doi.org/10.2174/1568026620666200516152756) (I.F-3.218)",
  },
  {
    _id: 4006,
    data: "6. Bharat Goel, Anuradha Sharma, Nancy Tripathi, Nivedita Bhardwaj, Bharat Sahu, Gurcharan Kaur, Bikarma Singh, & Shreyans K. Jain*, In-vitro antitumor activity of compounds from Glycyrrhiza glabra against C6 glioma cancer cells: identification of natural lead for further evaluation. Natural Product Research, 2020. (doi: https://doi.org/10.1080/14786419.2020.1786830) (I.F-2.158)",
  },
  {
    _id: 4007,
    data: "7. Manoj Kushwaha, Bharat Goel, Sundeep Jaglan, & Shreyans K. Jain*, LC-MS/MS profile of an active pharmaceutical ingredient and its impurities in commercial preparation. Journal of Liquid Chromatography & Related Technologies, 43, 2020: 131-137. (doi: https://doi.org/10.1080/10826076.2019.1680561) (I.F-0.992)",
  },
  {
    _id: 4008,
    data: "8. Priti Jain, Shreyans K. Jain, & Munendra Jain, Harnessing Drug Repurposing for Exploration of New Diseases: An Insight to Strategies and Case Studies. Current Molecular Medicine, 2020. (doi: https://doi.org/10.2174/1566524020666200619125404) (I.F-1.6)",
  },
];
export const researchData2019 = [
  {
    _id: 5001,
    data: "1. Rohit Singh, Kapil Mandrah, Ankita Asati, Devendra K. Patel, Bharat Goel, Ram A. Vishwakarma, Somendu K. Roy, & Shreyans K. Jain*, Transformation of Santonin to a Naproxen Analogue with Anti-Inflammatory Activity. Journal of Natural Products, 82, 2019: 1710-1713. (doi: https://doi.org/10.1021/acs.jnatprod.8b00318) (I.F-3.779)",
  },
  {
    _id: 5002,
    data: "2. P. Rajani, H. Aiswarya, M. M. Vasanthakumari, Shreyans K. Jain, Sandip B. Bharate, C. Rajasekaran, G. Ravikanth, & R. Uma Shaanker, Inhibition of the collar rot fungus, Sclerotium rolfsii Sacc. by an endophytic fungus Alternaria sp.: implications for biocontrol. Plant Physiology Reports, 24, 2019: 521-532. (doi: https://doi.org/10.1007/s40502-019-00484-6) (I.F-0.217)",
  },
  {
    _id: 5003,
    data: "3. Evan L. Pannkuk, Evagelia C. Laiakis, Kirandeep Gill, Shreyans K. Jain, Khyati Y. Mehta, Denise Nishita, Kim Bujold, James Bakke, Janet Gahagen, Simon Authier, Polly Chang, & Albert J. Fornace, Liquid Chromatography–Mass Spectrometry-Based Metabolomics of Nonhuman Primates after 4 Gy Total Body Radiation Exposure: Global Effects and Targeted Panels. Journal of Proteome Research, 18, 2019: 2260-2269. (doi: https://doi.org/10.1021/acs.jproteome.9b00101) (I.F-4.074)",
  },
  {
    _id: 5004,
    data: "4. Asma Derf, Shilpa A. Verekar, Shreyans K. Jain, Sunil K. Deshmukh, Sandip B. Bharate, & Bhabatosh Chaudhuri, Radicicol rescues yeast cell death triggered by expression of human α-synuclein and its A53T mutant, but not by human βA4 peptide and proapoptotic protein bax. Bioorganic Chemistry, 85, 2019: 152-158. (doi: https://doi.org/10.1016/j.bioorg.2018.12.033) (I.F-4.831)",
  },
  {
    _id: 5005,
    data: "5. Mohd Ishaq Dar, Priya Mahajan, Suraya Jan, Shreyans K. Jain, Harshita Tiwari, Jagjeet Sandey, Sandip Bharate, Amit Nargotra, & Sajad Hussain Syed, Rottlerin is a pan phosphodiesterase inhibitor and can induce neurodifferentiation in IMR-32 human neuroblastoma cells. European Journal of Pharmacology, 857, 2019: 172448. (doi: https://doi.org/10.1016/j.ejphar.2019.172448) (I.F-3.263)",
  },
];
export const researchData2018 = [
  {
    _id: 6001,
    data: "1. Keith Unger, Khyati Y. Mehta, Prabhjit Kaur, Yiwen Wang, Smrithi S. Menon, Shreyans K. Jain, Rose A. Moonjelly, Shubhankar Suman, Kamal Datta, Rajbir Singh, Paul Fogel, & Amrita K. Cheema, Metabolomics based predictive classifier for early detection of pancreatic ductal adenocarcinoma. Oncotarget, 9, 2018: 23078-23090. (doi: https://doi.org/10.18632/oncotarget.25212) (I.F-5.168)",
  },
  {
    _id: 6002,
    data: "2. N. Sharma, M. Kushwaha, D. Arora, Shreyans Jain, V. Singamaneni, S. Sharma, R. Shankar, S. Bhushan, P. Gupta, & S. Jaglan, New cytochalasin from Rosellinia sanctae-cruciana, an endophytic fungus of Albizia lebbeck. Journal of Applied Microbiology, 125, 2018: 111-120. (doi: https://doi.org/10.1111/jam.13764) (I.F-3.066)",
  },
  {
    _id: 6003,
    data: "3. Manoj Kushwaha, Shreyans K. Jain, Nisha Sharma, Vidushi Abrol, Sundeep Jaglan, & Ram A. Vishwakarma, Establishment of LCMS Based Platform for Discovery of Quorum Sensing Inhibitors: Signal Detection in Pseudomonas aeruginosa PAO1. ACS Chemical Biology, 13, 2018: 657-665. (doi: https://doi.org/10.1021/acschembio.7b00875) (I.F-4.434)",
  },
  {
    _id: 6004,
    data: "4. Amrita Cheema, Scott Grindrod, Simeng Suy, Xiaogang Zhong, Shreyans Jain, Khyati Mehta, Gaurav Bandi, Keith Kowalczyk, John Lynch, Sean Collins, & Anatoly Dritschilo, MP35-11 METABOLIC BIOMARKERS ARE PREDICTIVE OF RESPONSE TO RADIATION THERAPY IN PROSTATE CANCER PATIENTS. Journal of Urology, 199, 2018: e451-e451. (doi: https://doi.org/10.1016/j.juro.2018.02.1124) (I.F-5.92)",
  },
  {
    _id: 6005,
    data: "5. Sandip B. Bharate, Vikas Kumar, Shreyans K. Jain, Mubashir J. Mintoo, Santosh K. Guru, Vijay K. Nuthakki, Mohit Sharma, Sonali S. Bharate, Sumit G. Gandhi, Dilip M. Mondhe, Shashi Bhushan, & Ram A. Vishwakarma, Discovery and Preclinical Development of IIIM-290, an Orally Active Potent Cyclin-Dependent Kinase Inhibitor. Journal of Medicinal Chemistry, 61, 2018: 1664-1687. (doi: https://doi.org/10.1021/acs.jmedchem.7b01765) (I.F-6.2): (Equal contribution to first four anthours)",
  },
];
export const researchData2017 = [
  {
    _id: 7001,
    data: "1. Naveen Shivavedi, & Shreyans K Jain*, Review on the discovery of rohitukine-inspired CDK inhibitors. The Pharmstudent, 28, 2017: 50-58.",
  },
  {
    _id: 7002,
    data: "2. Rajni Sharma, Linda Gatchie, Ibidapo S. Williams, Shreyans K. Jain, Ram A. Vishwakarma, Bhabatosh Chaudhuri, & Sandip B. Bharate, Glycyrrhiza glabra extract and quercetin reverses cisplatin resistance in triple-negative MDA-MB-468 breast cancer cells via inhibition of cytochrome P450 1B1 enzyme. Bioorganic & Medicinal Chemistry Letters, 27, 2017: 5400-5403. (doi: https://doi.org/10.1016/j.bmcl.2017.11.013) (I.F-5.1)",
  },
  {
    _id: 7003,
    data: "3. Masroor Qadri, Yedukondalu Nalli, Shreyans K. Jain, Asha Chaubey, Asif Ali, Gary A. Strobel, Ram A. Vishwakarma, & Syed Riyaz-Ul-Hassan, An Insight into the Secondary Metabolism of Muscodor yucatanensis: Small-Molecule Epigenetic Modifiers Induce Expression of Secondary Metabolism-Related Genes and Production of New Metabolites in the Endophyte. Microbial Ecology, 73, 2017: 954-965. (doi: https://doi.org/10.1007/s40502-019-00484-6) (I.F-3.356)",
  },
  {
    _id: 7004,
    data: "4. Saima Khan, Pankaj Pandotra, Malik Muzafar Manzoor, Manoj Kushwaha, Rajni Sharma, Shreyansh Jain, Ashok Ahuja, Vishal Amancha, Sashi Bhushan, Santosh Kumar Guru, Ajai Prakash Gupta, Ram Vishwakarma, & Suphla Gupta, Terpenoid and flavonoid spectrum of in vitro cultures of Glycyrrhiza glabra revealed high chemical heterogeneity: platform to understand biosynthesis. Plant Cell, Tissue and Organ Culture (PCTOC), 124, 2016: 507-516. (doi: https://doi.org/10.1007/s11240-015-0910-4) (I.F-2.196)",
  },
  {
    _id: 7005,
    data: "5. Vikas Kumar, Santosh K. Guru, Shreyans K. Jain, Prashant Joshi, Sumit G. Gandhi, Sandip B. Bharate, Shashi Bhushan, Sonali S. Bharate, & Ram A. Vishwakarma, A chromatography-free isolation of rohitukine from leaves of Dysoxylum binectariferum: Evaluation for in vitro cytotoxicity, Cdk inhibition and physicochemical properties. Bioorganic & Medicinal Chemistry Letters, 26, 2016: 3457-3463. (doi: https://doi.org/10.1016/j.bmcl.2016.06.046) (I.F-5.1)",
  },
  {
    _id: 7006,
    data: "6. Samdarshi Meena, Rohit Singh, Ram A. Vishwakarma, Mushtaq A. Aga, & Shreyans K. Jain*, SeO2 mediated efficient synthesis of amides and α-ketoamides of secondary amines with wide substrate scope. Tetrahedron Letters, 57, 2016: 3715-3717. (doi: https://doi.org/10.1016/j.tetlet.2016.06.129) (I.F-2.275)",
  },
  {
    _id: 7007,
    data: "7. Rajni Sharma, Santosh K. Guru, Shreyans K. Jain, Anup Singh Pathania, Ram A. Vishwakarma, Shashi Bhushan, & Sandip B. Bharate, 3-(2,6-Dichloro-benzyloxy)-11-oxo-olean-12-ene-29-oic acid, a semisynthetic derivative of glycyrrhetic acid: synthesis, antiproliferative, apoptotic and anti-angiogenesis activity. MedChemComm, 6, 2015: 564-575. (doi: https://doi.org/10.1039/C4MD00344F) (I.F-2.394)",
  },
  {
    _id: 7008,
    data: "8. Baljinder Singh, Shreyans K. Jain, Sandip B. Bharate, Manoj Kushwaha, Ajai Prakash Gupta, & Ram A. Vishwakarma, Simultaneous Quantification of Five Bioactive Flavonoids in High Altitude Plant Actinocarya tibetica by LC-ESI-MS/MS. Journal of AOAC INTERNATIONAL, 98, 2015: 907-912. (doi: https://doi.org/10.5740/jaoacint.14-270) (I.F-1.510)",
  },
  {
    _id: 7009,
    data: "9. Shreyans K. Jain, K. A. Aravinda Kumar, Sandip B. Bharate, & Ram A. Vishwakarma, Facile access to amides and hydroxamic acids directly from nitroarenes. Organic & Biomolecular Chemistry, 12, 2014: 6465-6469. (doi: https://doi.org/10.1039/C4OB01155D) (I.F-3.41)",
  },
  {
    _id: 7010,
    data: "10. Shreyans K. Jain, Samdarshi Meena, Ajai P. Gupta, Manoj Kushwaha, R. Uma Shaanker, Sundeep Jaglan, Sandip B. Bharate, & Ram A. Vishwakarma, Dysoxylum binectariferum bark as a new source of anticancer drug camptothecin: Bioactivity-guided isolation and LCMS-based quantification. Bioorganic & Medicinal Chemistry Letters, 24, 2014: 3146-3149. (doi: https://doi.org/10.1016/j.bmcl.2014.05.001) (I.F-2.572)",
  },
  {
    _id: 7011,
    data: "11. Shreyans K. Jain, Surjeet Singh, Anamika Khajuria, Santosh K. Guru, Prashant Joshi, Samdarshi Meena, Janhavi R. Nadkarni, Amarinder Singh, Sonali S. Bharate, Shashi Bhushan, Sandip B. Bharate, & Ram A. Vishwakarma, Pyrano-isochromanones as IL-6 Inhibitors: Synthesis, in Vitro and in Vivo Antiarthritic Activity. Journal of Medicinal Chemistry, 57, 2014: 7085-7097. (doi: https://doi.org/10.1021/jm500901e) (I.F-6.205)",
  },
  {
    _id: 7012,
    data: "12. Prashant Joshi, Samsher Singh, Abubakar Wani, Sadhana Sharma, Shreyans K. Jain, Baljinder Singh, Bishan D. Gupta, Naresh K. Satti, Surrinder Koul, Inshad A. Khan, Ajay Kumar, Sandip B. Bharate, & Ram A. Vishwakarma, Osthol and curcumin as inhibitors of human Pgp and multidrug efflux pumps of Staphylococcus aureus: reversing the resistance against frontline antibacterial drugs. MedChemComm, 5, 2014: 1540-1547. (doi: https://doi.org/10.1039/C4MD00196F) (I.F-2.394)",
  },
  {
    _id: 7013,
    data: "13. Jaideep B. Bharate, Santosh K. Guru, Shreyans K. Jain, Samdarshi Meena, Parvinder Pal Singh, Shashi Bhushan, Baldev Singh, Sandip B. Bharate, & Ram A. Vishwakarma, Cu–Mn spinel oxide catalyzed synthesis of imidazo[1,2-a]pyridines through domino three-component coupling and 5-exo-dig cyclization in water. RSC Advances, 3, 2013: 20869-20876. (doi: https://doi.org/10.1039/C3RA42046A) (I.F-3.119)",
  },
  {
    _id: 7014,
    data: "14. Sandip B. Bharate, Baljinder Singh, Jaideep B. Bharate, Shreyans K. Jain, Samdarshi Meena, & Ram A. Vishwakarma, QSAR and pharmacophore modeling of N-acetyl-2-aminobenzothiazole class of phosphoinositide-3-kinase-α inhibitors. Medicinal Chemistry Research, 22, 2013: 890-899. (doi: https://doi.org/10.1007/s00044-012-0081-3) (I.F-1.783)",
  },
  {
    _id: 7015,
    data: "15. Shreyans K. Jain, Samdarshi Meena, Asif K. Qazi, Aashiq Hussain, Sunil K. Bhola, Rajendra Kshirsagar, Koteppa Pari, Anamika Khajuria, Abid Hamid, R. Uma Shaanker, Sandip B. Bharate, & Ram A. Vishwakarma, Isolation and biological evaluation of chromone alkaloid dysoline, a new regioisomer of rohitukine from Dysoxylum binectariferum. Tetrahedron Letters, 54, 2013: 7140-7143. (doi: https://doi.org/10.1016/j.tetlet.2013.10.096) (I.F-2.275)",
  },
  {
    _id: 7016,
    data: "16. Shreyans K. Jain, Anup S. Pathania, Samdarshi Meena, Rajni Sharma, Ashok Sharma, Baljinder Singh, Bishan D. Gupta, Shashi Bhushan, Sandip B. Bharate, & Ram A. Vishwakarma, Semisynthesis of Mallotus B from Rottlerin: Evaluation of Cytotoxicity and Apoptosis-Inducing Activity. Journal of Natural Products, 76, 2013: 1724-1730. (doi: https://doi.org/10.1021/np400433g) (I.F-3.779)",
  },
  {
    _id: 7017,
    data: "17. Shreyans K. Jain, Anup S. Pathania, Rajinder Parshad, Chandji Raina, Asif Ali, Ajai P. Gupta, Manoj Kushwaha, Subrayashastry Aravinda, Shashi Bhushan, Sandip B. Bharate, & Ram A. Vishwakarma, Chrysomycins A–C, antileukemic naphthocoumarins from Streptomyces sporoverrucosus. RSC Advances, 3, 2013: 21046-21053. (doi: https://doi.org/10.1039/C3RA42884B) (I.F-3.119)",
  },
  {
    _id: 7018,
    data: "18. P. Mishra, Shilpa Verekar, Asha Kulkarni-Almeida, Somendu Roy, Shreyans Jain, Arun Balakrishnan, R. Vishwakarma, & Sunil Deshmukh, Anti-inflammatory and anti-diabetic naphtha quinones from an endophytic fungus Dendryphion nanum (Nees) S. Hughes. Indian Journal of Chemistry Section B, 52B, 2013: 565-567. (I.F-0.388)",
  },
  {
    _id: 7019,
    data: "19. Baljinder Singh, Santosh K. Guru, Smit Kour, Shreyans K. Jain, Rajni Sharma, Parduman R. Sharma, Shashank K. Singh, Shashi Bhushan, Sandip B. Bharate, & Ram A. Vishwakarma, Synthesis, antiproliferative and apoptosis-inducing activity of thiazolo[5,4-d]pyrimidines. European Journal of Medicinal Chemistry, 70, 2013: 864-874. (doi: https://doi.org/10.1016/j.ejmech.2013.10.039) (I.F-5.572)",
  },
  {
    _id: 7020,
    data: "20. Baljinder Singh, Tabasum Sidiq, Prashant Joshi, Shreyans K. Jain, Yogesh Lawaniya, Surinder Kichlu, Anamika Khajuria, Ram A. Vishwakarma, & Sandip B. Bharate, Anti-inflammatory and immunomodulatory flavones from Actinocarya tibetica Benth. Natural Product Research, 27, 2013: 2227-2230. (doi: https://doi.org/10.1080/14786419.2013.805334) (I.F-2.158)",
  },
  {
    _id: 7021,
    data: "21. Shreyans Kumar Jain, Sandip B. Bharate, & Ram A. Vishwakarma, Cyclin-Dependent Kinase Inhibition by Flavoalkaloids. Mini-Reviews in Medicinal Chemistry, 12, 2012: 632-649. (doi: http://dx.doi.org/10.2174/138955712800626683) (I.F-2.73)",
  },
  {
    _id: 7022,
    data: "22. Shreyans K. Jain, Samdarshi Meena, Baljinder Singh, Jaideep B. Bharate, Prashant Joshi, Varun P. Singh, Ram A. Vishwakarma, & Sandip B. Bharate, KF/alumina catalyzed regioselective benzylation and benzoylation using solvent-free grind-stone chemistry. RSC Advances, 2, 2012: 8929-8933. (doi: https://doi.org/10.1021/np400433g) (I.F-3.119)",
  },
  {
    _id: 7023,
    data: "23. Ramesh Mudududdla, Shreyans K. Jain, Jaideep B. Bharate, Ajai P. Gupta, Baldev Singh, Ram A. Vishwakarma, & Sandip B. Bharate, ortho-Amidoalkylation of Phenols via Tandem One-Pot Approach Involving Oxazine Intermediate. The Journal of Organic Chemistry, 77, 2012: 8821-8827. (doi: https://doi.org/10.1021/jo3017132) (I.F-4.335)",
  },
  {
    _id: 7024,
    data: "24. Inder Pal Singh, Shreyans Kumar Jain, Amandeep Kaur, Sukhvinder Singh, Rajender Kumar, Prabha Garg, Shyam Sundar Sharma, & Sunil Kumar Arora, Synthesis and Antileishmanial activity of Piperoyl-Amino Acid Conjugates. European Journal of Medicinal Chemistry, 45, 2010: 3439-3445. (doi: https://doi.org/10.1016/j.ejmech.2010.04.033) (I.F-5.572)",
  },
];
export const monographs = [
  {
    _id: "8001",
    title: "WITHANIA (INDIAN GINSENG)",
    introduction:
      "Withania somnifera Dunal. mature roots are called ‘Aswagandha dravya’. It is an Indian perennial shrub that grows in waste areas, fields, and open spaces all throughout the country. It is particularly popular in parts of Madhya Pradesh and Rajasthan, where roots are harvested in the winter, cleaned, and cut into small pieces.",
    botanicalName: "Withania somnifera",
    family: "Solanaceae",
    vernacularNames: [
      [
        "Sanskrit",
        "Hayagandha, Vajigandha",
        "Kannada",
        "Angarberu, Hiremaddinagida",
      ],
      ["Assamese", "Ashvagandha", "Kashmiri", "Asagandh"],
      ["Bengali", "Ashvagandha", "Malayalam", "Amukkuram"],
      ["English", "Gujrati", "Hindi", "Tamil"],
      ["Indian winter cherry", "Asgandha", "Asgandh", "Amukkaramkizangu"],
    ],
    literature: [
      [
        "1",
        "Schizophrenia",
        "WS extract (Sensoril®) & Placebo Oral Tablet",
        "Phase 2, Phase 3",
        "Stephen Marder, University of California,Los Angeles",
        "Randomized study, parallel assignment, Quadruple masking with 66 participants, started on December 1 st , 2018",
        "NCT03437668",
      ],
      [
        "2",
        "Obesity",
        "Cinnamomum cassia (CC) and Withania som nifera (WS) (300mg + 150mg, respectively) & Placebo",
        "N/A",
        "Lucio Gnessi, University of Roma La Sapienza",
        "Randomized allocation, Crossover Assignment, Quadruple masking with 40 participants pilot study, started on January 1 st , 2018",
        "NCT05210218",
      ],
      [
        "3",
        "Cognitive Impairment, Mild",
        "Andrographis and Withania & Placebo",
        "Phase 1",
        "EuroPharma, Inc.",
        "Randomized, Crossover Assignment, triple masking with 16 participants double blind study started on April 1 st , 2019",
        "NCT03780621",
      ],
      [
        "4",
        "Schizophrenia & Schizoaffective Disorder",
        "WS extract (Sensoril®) & Placebo",
        "N/A",
        "K.N. Roy Chengappa, Professor of Psychiatry, University of Pittsburgh",
        "Randomized, parallel assignment, Quadruple masking with 68 participants started on April 2013",
        "NCT01793935",
      ],
      [
        "5",
        "Chronic Periodontitis",
        "Ashwagandha & Placebo",
        "Phase 1, Phase 2",
        "Dr.Nibha Suneel Kulkarni, Tatyasaheb Kore Dental College,",
        "Randomized study, parallel assignment, double masking, with 50 participants started on November 30 th , 2017",
        "NCT03533972",
      ],
      [
        "6",
        "Amyotrophic Lateral Sclerosis",
        "Withania somnifera & Placebo",
        "Phase 2",
        "Sunnybrook Health Sciences Centre, Ontario, Canada.",
        "Randomized, parallel assignment, Quadruple study including 75 participants, started on October 19, 2021",
        "NCT05031351",
      ],
      [
        "7",
        "Immune Health",
        "Aqueous extract of roots plus leaves of Withania somnifera & Microcrystalline Cellulose",
        "N/A",
        "Vedic Lifesciences Pvt. Ltd.",
        "Randomized, Parallel Assignment, Quadruple masking with 77 participants started on 21 st January, 2021",
        "NCT04733924",
      ],
      [
        "8",
        "Generalized Anxiety Disorder",
        "Sensoril® & Placebo",
        "Phase 2",
        "Natreon, Inc.",
        "Randomized parallel Assignment, Double masking started on march 2021, with 120 participants.",
        "NCT01311180",
      ],
      [
        "9",
        "Stress Sleep Craving Well Being",
        "Ashwagandha & Placebo",
        "Phase 2",
        "Margaret Harris, University of Colorado, Colorado Springs",
        "Randomized parallel Assignment, Quadruple masking, started on May 29, 2019 including 60 participants",
        "NCT05430685",
      ],
      [
        "10",
        "Hypercholest erolemia",
        "Ayurveda formulation containing Terminalia Arjuna, Withania Sominifera, Garcinia Cambogia and piperine",
        "N/A",
        "NMP Medical Research Institute",
        "Single Group Assignment with 22 participants, started on June 1, 2021",
        "NCT04974853",
      ],
      [
        "11",
        "Bipolar I Disorder, Bipolar II Disorder, Bipolar Disorder NOS",
        "Sensoril & Placebo",
        "Phase 3",
        "K.N. Roy Chengappa, Professor of Psychiatry, University of Pittsburgh",
        "Randomized study, parallel Assignment, quadruple masking, on 60 participants, started on October 2008",
        "NCT00761761",
      ],
      [
        "12",
        "Periodontitis",
        "Adaptogenic herbs (Panax ginseng, Withania somnifera and Eleutherococcus senticosus) & glutamine",
        "Phase 2",
        "National Center for Complementary and Integrative Health (NCCIH)",
        "Randomized trial started on September 1999.",
        "NCT00010634",
      ],
      [
        "13",
        "Coronary Artery Disease, Cerebro Vascular Disease, Ischemic Heart Disease, Deep Vein Thrombosis, Peripheral Arterial Diseases, Vascular Disease",
        "SUVED (Terminalia Arjuna: Withania somnifera; Terminalia chebula; Cyperus rotundus; Apium graveolens; Vitis vinifera; Piper longum; Fagonia Arabica; Emblica officinalis; Terminalia belerica; Nymphaea stellata; Punica granatum; Bacopa Monnieri; and stabilizing herbs), REIMMUGEN, Grain flour placebo",
        "Phase 3",
        "Sujata Vaidya, Health Solutions, India",
        "Randomized, parallel Assignment Double Blind, triple masking study with 96 participants, started on January 2016.",
        "NCT02920125",
      ],
      [
        "14",
        "Skin Abnormalities",
        "Ashwagandha (Withania somnifera) root and leaf extract",
        "N/A",
        "Raja K Sivamani, MD Integrative Skin Science and Research Institute",
        "Randomized parallel Assignment, Open Label study with 74 participants started on November 26,2019",
        "NCT04872946",
      ],
    ],
    preclinical: [
      [
        "1",
        "Anti-stressor",
        "Aqueous root extract of WS (100 mg/kg dosage) administered orally.",
        "Adult Wistar strain albino rats of either sex were examined with stress indices like Plasma Corticosterone(mg/dl), Phagocytic index, Avidity index, Total swimming time (min) were calculated.",
        "Archana, R. and Namasivayam, A., 1998. Antistressor effect of Withania somnifera. Journal of ethnopharmacology, 64(1), 91-93.",
      ],
      [
        "2",
        "Anxiolytic-antidepressant activity",
        "Bioactive glycowithanolides isolated from the roots of WS (20 and 50 mg/kg), administered orally.",
        "Elevated plus-maze test, Social Interaction test, Novelty-suppressed feeding latency test and Rat brain tribulin activity for Anxiolytic activity, andSwim stress-induced 'behavioural despair' test, Learned helplessness test and Rotarod test for examining anti-depressant activity.",
        "Bhattacharya, S.K., Bhattacharya, A., Sairam, K. and Ghosal, S., 2000. Anxiolytic-antidepressant activity of Withania somnifera glycowithanolides: an experimental study. Phytomedicine, 7(6), 463-469.",
      ],
      [
        "3",
        "Anticancer activity",
        "Derivatives of Withaferin A type of withanolides isolated from the chloroform extract of WS",
        "MTT assay for in vitro cytotoxicity against four human cancer cell linesWRL68, CaCO-2, PC-3 and MCF7",
        "Joshi, P., Misra, L., Siddique, A.A., Srivastava, M., Kumar, S. and Darokar, M.P., 2014. Epoxide group relationship with cytotoxicity in withanolide derivatives from Withania somnifera. Steroids, 79, 19-27.",
      ],
      [
        "4",
        "Immunomodulatory and CNS Effects",
        "Two glycowithanolides, sitoindoside IX and sitoindoside X, isolated from WS roots extract.",
        "Swiss mice and Wistar strain albino rats were used to study Fc receptor expression, phagocytosis by macrophages, Tumor growth and tumour-associated macrophages, effects on the central nervous system and acute toxicity.",
        "Ghosal, S., Lal, J., Srivastava, R., Bhattacharya, S.K., Upadhyay, S.N., Jaiswal, A.K. and Chattopadhyay, U., 1989. Immunomodulatory and CNS effects of sitoindosides IX and X, two new glycowithanolides from Withania somnifera. Phytotherapy Research, 3(5), 201-206.",
      ],
      [
        "5",
        "Anti-tumoural activity",
        "Hydroalcoholic extracts from the roots & leaves of WS.",
        "In vitro cytotoxicity study against a panel of human cancer cell line, sulphorhodamine B (SRB) protein binding assay, flow cytometric analysis, analysis of sub-G 0 /G 1 population, measurement of mitochondrial membrane potential, caspase assays, western blot analysis, Ehrlich Ascites Carcinoma (EAC), Ehrlich Ascites Tumour (EAT solid) studies were done using BALB/c and Swiss albino mice.",
        "Malik, F., Kumar, A., Bhushan, S., Mondhe, D.M., Pal, H.C., Sharma, R., Khajuria, A., Singh, S., Singh, G., Saxena, A.K. and Suri, K.A., 2009. Immune modulation and apoptosis induction: Two sides of antitumoural activity of a standardised herbal formulation of Withania somnifera. European Journal of Cancer, 45(8), 1494-1509.",
      ],
      [
        "6",
        "Immunomodulatory activity",
        "Methanol extract of root of WS",
        "Balb/c mice were used for the determination of effect of Withania somnifera on the haematological parameters, organ weight of mice, the bone marrow cellularity and a-esterase positive cells, circulating antibody titre, the antibody producing cells, delayed type hypersenstivity reaction (DTH) and the phagocytic activity of macrophages.",
        "Davis, L. and Kuttan, G., 2000. Immunomodulatory activity of Withania somnifera. Journal of ethnopharmacology, 71(1-2), 193-200.",
      ],
      [
        "7",
        "Anti-granuloma activity",
        "Extract of WS aerial parts",
        "Albino male Wistar rats were used for the Cotton-pellet granuloma assay.",
        "Al-Hindawi, M.K., Al-Khafaji, S.H. and Abdul-Nabi, M.H., 1992. Anti-granuloma activity of Iraqi Withania somnifera. Journal of ethnopharmacology, 37(2), 113-116.",
      ],
      [
        "8",
        "Adaptogenic activity",
        "Extract of WS roots",
        "Adult male Wistar strain rats were used to examine the gastric ulceration, behavioural depression, cognitive functions, sexual behavior, immune function and biochemical investigations.",
        "Bhattacharya, S.K. and Muruganandam, A.V., 2003. Adaptogenic activity of Withania somnifera: an experimental study using a rat model of chronic stress. Pharmacology Biochemistry and Behavior, 75(3), 547-555.",
      ],
    ],
  },
  {
    _id: "8002",
    title: "LIQUORICE",
    introduction:
      "Glycyrrhiza glabra Linn. belongs to the family leguminosae. Its unpeeled dried stolons and roots are used as herbal drugs. The tree is upto 2 m tall perennial herb that is grown across Europe, Afghanistan, Persia and to alesser extent in some regions of India.",
    botanicalName: "Glycyrrhiza glabra",
    family: "Leguminosae",
    vernacularNames: [
      [
        "Sanskrit",
        "Yastimadhuka, Yastika,Madhuka, madhuyasti, Yastyahva",
        "Kannada",
        "Jestamadu, Madhuka,Jyeshtamadhu, Atimadhura",
      ],
      ["Assamese", "Jesthimadhu, Yeshtmadhu", "Kashmiri", "Multhi"],
      ["Bengali", "Yashtimadhu", "Malayalam", "Irattimadhuram"],
      [
        "English",
        "Liquorice root",
        "Hindi",
        "Mulethi, Mulathi, Muleti,Jethimadhu, Jethimadh",
      ],
      ["Punjabi", "Jethimadh, Mulathi", "Telugu", "Atimadhuramu"],
    ],
    literature: [
      [
        "1",
        "Apparent Mineralocorti coid Excess",
        "Dietary Supplement: Liquorice",
        "N/A",
        "Rousseau Gama,The Royal Wolverhampton NHS Trust",
        "A Single Group Open Label investigation including 12 participants started on November 2016.",
        "NCT02939144",
      ],
      [
        "2",
        "Oral Lichen Planus",
        "Licorice &amp; Triamcinolone Acetonide comparative study",
        "Phase 2",
        "Mehdi Nasr Isfahani, Director, Isfahan University of Medical Sciences",
        "A Randomized parallel comparative study with double masking with 60 participants started on January 2014.",
        "NCT02453503",
      ],
      [
        "3",
        "Sore Throat",
        "licorice solution (0.5g) &amp; sugar solution",
        "N/A",
        "Daniel Sessler, Outcomes Research Consortium, Cleveland Clinic",
        "Randomized, parallel, doubleblind investigation with 236 participants started on October 2010",
        "NCT01444703",
      ],
      [
        "4",
        "Addison Disease",
        "Liquorice &amp; Grapefruit Juice",
        "N/A",
        "Helse-Bergen HF, Haukeland University Hospital",
        "Randomized, crossover, open label study including 17 participants started on April 2008",
        "NCT01271296",
      ],
      [
        "5",
        "High Caries Risk patients, Antimicrobial Effect",
        "Arabic, Gum, Liquorice  Root, Chlorhexidine",
        "Phase 2 &amp; Phase 3",
        "Dina Mohame, Kamal Eldin, Cairo University",
        "63 participants randomized parallel Assignment, triple masking started on December 10, 2019",
        "NCT03684993",
      ],
      [
        "6",
        "Mucositis",
        "Triamcinolone Acetonide &amp; licorice mucoadhesive films",
        "Phase 1 &amp; Phase 2",
        "Mehdi Nasr Isfahani, Isfahan University of Medical Sciences",
        "60 participants randomized, parallel assignment, double blind masking study for supportive care started on May 2013",
        "NCT02075749",
      ],
      [
        "7",
        "Hypokalemia",
        "Hydrochlorothiazide &amp; Licorice",
        "Phase 4",
        "Markku Savolainen, MD, Oulu University Hospital",
        "10 participants Randomized, crossover Assignment, open label study started on February 2008",
        "NCT00605202",
      ],
      [
        "8",
        "Oligospermia",
        "ChandrakanthiChoornam (CKC) containing Glycyrrhiza glabra root",
        "Phase 2",
        "Dr. B. Akila., M.D, Tamil Nadu, Dr. M. G.R. Medical University",
        "40 participants, single group, open label study for treatment purpose, started on December 2012.",
        "NCT02234206",
      ],
      [
        "9",
        "Acute stroke",
        "Licorice whole extract",
        "Phase 1 &amp; Phase 2",
        "Afshin Borhani- Haghighi, Shiraz University of Medical Sciences",
        "75 participants, randomized parallel, quadruple study started on June 2012.",
        "NCT02473458",
      ],
      [
        "10",
        "Dental Caries",
        "Licorice",
        "N/A",
        "Sara Mohammed Ahmed Mady, Cairo University",
        "81 participants randomized, parallelAssignment, quadruple study started on September 1, 2020.",
        "NCT03763578",
      ],
      [
        "11",
        "COVID-19",
        "Licorice extract",
        "N/A",
        "Adel Gomaa, Egyptian Biomedical Research Network",
        "50 participants, randomized, Parallel, open label, pilot study started on January 1, 2020.",
        "NCT04487964",
      ],
      [
        "12",
        "Mild Gingivitis, Periodontal Diseases, Plaque",
        "Licorice, Hypertonic salt solution, Essential oil, Chlorhexidine Gluconate",
        "N/A",
        "Dr. Ruchi Gulati, Government College of Dentistry, Indore",
        "35 participants Randomized, cross over study by triple masking started on August 2016",
        "NCT03550651",
      ],
      [
        "13",
        "Schizophrenia, Schizophrenic Disorder, Hyperprolactinemia, Hyperprolactinaemia",
        "Peony- Glycyrrhiza Decoction(PGD) granules",
        "Phase 2",
        "Prof. Zhang Zhang-Jin, The University of Hong Kong",
        "103 participants Randomized, parallel study with quadruple masking started on January 2013.",
        "NCT01852331",
      ],
      [
        "14",
        "Covid19, Immunodeficiency",
        "Omega 3/Nigella Sativa Oil, Indian Costus, Quinine pills, Anise seed capsule, Deglycyrrhizinated Licorice",
        "Phase 2 &amp; Phase 3",
        "Mohamed Medhat Abdelwahab Gamaleldin, Beni-Suef University",
        "150 participants randomized sequential study with double masking (Participant, Care taker) for treatment purpose started on September 20, 2020",
        "NCT04553705",
      ],
      [
        "15",
        "Apparent Mineralocorticoid Excess (AME)",
        "Glycyrrhetic Acid",
        "Phase 2 &amp; Phase 3",
        "Joshua A. Beckman, MD, Brigham and Women&#39;s Hospital",
        "15 participants randomized crossover, quadruple masking study started on February 2002",
        "NCT00759525",
      ],
      [
        "16",
        "Chronic Periodontitis",
        "Cocktail from complex phytoadaptogens (CFA) containing glycyrrhiza",
        "Phase 4",
        "Vladikavkaz Scientific Center of the Russian Academy of Sciences",
        "30 participants randomized crossover study with quadruple masking, started on February 1, 2019",
        "NCT04623164",
      ],
      [
        "17",
        "End Stage Renal Disease",
        "Oral 18B Glycyrrhetinic acid versus placebo",
        "Phase 2",
        "University Hospital Inselspital, Berne",
        "24 participants Randomized crossover study with double masking started on August 2006",
        "NCT00384384",
      ],
    ],
  },
  {
    _id: "8003",
    title: "BLACK PEPPER",
    introduction:
      "Black pepper is a woody climber grown in the south western region of India, comprising of the states of Kerala, parts of Karnataka, Tamil Nadu and Goa, the entire region once known as Malabar. This spice with its characteristic pungency and flavour is an ingredient in many food preparations.",
    botanicalName: "Piper Nigrum",
    family: "Piperaceae",
    morphology: [
      ["Type of the plant", "Woody climber"],
      ["Height of the plant", "10 metres (33 feet)"],
      [
        "Leaves and flowers",
        "Broad and shiny green leaves which are alternately arranged. The small flowers are in dense slender spikes of about 50 blossoms each.",
      ],
      [
        "Fruit and seed",
        "The fruits, are drupes about 5 mm (0.2 inch) in diameter. They become yellowish red at maturity. The fruits are picked when they begin to turn red; The collected fruits are immersed in boiling water for about 10 minutes, which causes them to turn dark brown or black in an hour. Then they are dried and yield black pepper.",
      ],
      [
        "Odour and Taste",
        "The odour is penetrating and aromatic; the taste is hot, biting and very pungent.",
      ],
    ],
    vernacularNames: [
      [
        "Hindi",
        "Kalimirch, Mirch, Gulmirch, Golmirch",
        "English",
        "Black pepper, Common pepper, pepper",
      ],
      [
        "Telugu",
        "JMiriyalu, marichamu, shavyamu",
        "Bengali",
        "Golmarich, vellajung, Muricha, kala morich",
      ],
      ["Tamil", "Milagu", "Marathi", "Mirin, kalamiri"],
      ["Gujarati", "Kalamri, kalamuri, kolamire", "Kannada", "Kari Manesu"],
      ["Malayalam", "Nalla muluka", "Konkani", "Kare Menasu"],
      ["Urdu", "Kalimirch", "Punjabi", "Galmirch"],
    ],
    literature: [
      [
        "1",
        "Pain",
        "Turmeric Turmeric + Black Pepper",
        "N/A",
        "Daniel L. Smith, Jr., University of Alabama at Birmingham",
        "Clinical type; Randomized allocation with 30 participants",
        "NCT05206266",
      ],
      [
        "2",
        "Obesity",
        "24-hour energy expenditure and substrate utilization",
        "N/A",
        "University of North Carolina, Chapel Hill",
        "Clinical type; Randomized allocation with 18 participants",
        "NCT01729143",
      ],
      [
        "3",
        "Absorption Carotenoid",
        "salad dressing (canola oil, sunflower oil, olive oil, corn oil, flaxseed) and black pepper",
        "N/A",
        "University of Massachusetts, Amherst",
        "Clinical Trial; Randomized study with 16 participants",
        "NCT03490955",
      ],
      [
        "4",
        "Vein; Spasm Patient Satisfaction NurseScope, Practice",
        "Topical essential oil application",
        "N/A",
        "Handan Eren, University of Yalova",
        "Clinical Trial; Randomized study with 60 participants",
        "NCT04796805",
      ],
      [
        "5",
        "Waist Circumference Triglycerides Appetite Inflammation Lipids",
        "Dietary Supplement: Black pepper extract",
        "N/A",
        "The Center for Applied Health Sciences, LLC",
        "Clinical trial; Randomized allocation with 94 patients",
        "NCT05199012",
      ],
      [
        "6",
        "Healthy",
        "Dietary Supplement: ginger, black pepper , horseradish, mustard, placebo",
        "N/A",
        "University of Copenhagen",
        "Clinical trial; Randomized allocation with 22 participants",
        "NCT00611156",
      ],
    ],
  },
];

export const courses = [
  ["UG", "Biology", "BL-101", "UG", "Pharm Chem", "PH-221"],
  [
    "PG",
    "Computational Drug Design",
    "PH-525",
    "UG",
    "Essentials of Biochem",
    "CY-103",
  ],
  [
    "PG",
    "Advanced Medicinal Chemistry",
    "PH-521",
    "PG",
    "Chemistry of Natural Products",
    "PH-523",
  ],
  [
    "UG",
    " Chemistry of Natural Drugs",
    "PH-322",
    "UG",
    "Industrial Pharmacognosy",
    "PH-342",
  ],
  [
    "UG",
    "Analytical Pharmacognosy",
    "PH-442",
    "UG",
    "Princ & Tech of Mol Biol.",
    "PH-323",
  ],
  [
    "UG",
    "Natural Drugs and Excipients",
    "PH-341",
    "UG",
    "Plant Tissue culture",
    "PH-441",
  ],
  [
    "UG",
    "Chemistry of Natural Drugs",
    "PH-322",
    "UG",
    "Natural Drugs and Excipients",
    "PH-341",
  ],
  [
    "UG",
    "Natural Drug and Phytotherapy",
    "PH-441",
    "PG",
    "Advances in drug synthesis",
    "PH-522",
  ],
];


export const NPdata = [
    [
    "1",
    "rutin",
    "C[C@H]1[C@@H]([C@H]([C@O",
    "IKGXIBQEEMLURG-RZIXAHTPSA-N",
    "6.633, 16.858, 11.864, 12.886, 7.594, 18.985, 13.672, 16.991, 13.111, 19.031",
    "610.519",
    "-1.2573",
    "-2.398",
    "16",
    "10",
    "397.71",
    "1.9337"
  ],
  [
    "2",
    "piperine",
    "C1CCN(CC1)C(=O)/C=C/C=C/C2=CC3=C(C=C2)OCO3",
    "MXXWOMGUGJBKIW-UHFFFAOYSA-N",
    "N/A",
    "285.342",
    "3.5951",
    "-3.608",
    "4",
    "0",
    "229.87",
    "0.43286"
  ],
  [
    "3",
    "rottlerin",
    "CC1=C(C(=C(C(=C1O)C(=O)C)O)CC4)O)O",
    "DEZFNHCVIZBHBI-UHFFFAOYSA-N",
    "6.257, 11.524, 8.122, 15.009, 12.008",
    "516.544",
    "4.633",
    "-6.358",
    "8	",
    "5",
    "382.74",
    "-1.3931",
  ],
  [
    "4",
    "rohitukin",
    "CC(C)CC(=O)OC1C(C(C(=C)C2(C)C)C)OC = O",
    "BGIQNWKPRGQOMD - UHFFFAOYSA - N",
    "11.33",
    "658.694",
    "2.3244",
    "- 5.453",
    "13",
    "1",
    "	467.84",
    "- 2.8059",
  ],
  [
    "5",
    "Colchicine",
    "CC(=O)N[C@H]1CCC2 = CC(=C(C(=C2C3 = CC = C(C(=O)C = C13)OC)OC)OC)OC",
    "IAKHMKGGTNLKSZ - INIZCTEOSA - N",
    "N / A",
    "399.442",
    "1.863",
    "- 3.046",
    "7",
    "1",
    "308.67",
    "1.024",
  ],
  [
    "6",
    "ergosterol peroxide",
    "CC(=O)N[C@H]1CCC2 = CC(=C(C",
    "IAKHMKGGTNLKSZ - INIZCTEOSA - N",
    "5.127, 11.784, 11.784, 5.127	",
    "302.194",
    "1.2774",
    "- 3.286",
    "8",
    "4",
    "186.92",
    "- 1.5983",
  ],
  [
    "7",
    "tannic acid",
    "C1 = C(C = C(C(=C1O)O)",
    "LRBQNJMCXXYXIU - WKMQCYIUSA - N",
    "6.104, 7.517, 7.517, 12.769, 16.929, 12.712, 6.128, 12.731, 12.740, 12.781, 6.129, 6.138, 6.198, 7.516, 7.516, 16.929, 7.516, 7.516, 7.516, 7.516, 7.519, 7.519, 16.929, 16.929, 16.930",
    "1701.2",
    "5.5312",
    "- 7.599",
    "46",
    "25",
    "1120.1",
    "- 0.25527"
  ],
  [
    "8",
    "lupeol",
    "CC(=C)[C@@H]1CC[C@]2([C@H]1[C@H]3C",
    "MQYXUWHLBZFQQO - DCTTWMPASA - N",
    "14.67",
    "426.726",
    "7.6469",
    "- 6.803",
    "1",
    "1",
    "325.57",
    "- 22.172"
  ],

  [
    "9",
    "neoandrographolide",
    "C[C@]1(CCC[C@@]2([C@@H]1CCC(=C)[",
    "YGCYRQKJYWQXHG - KFHWRKOBSA - N	",
    "17.435, 13.077, 20.685, 14.965",
    "480.596	",
    "1.7385",
    "- 3.451",
    "8",
    "4",
    "350.55",
    "- 7.3728",
  ],
  [
    "10",
    "ellagic acid",
    "C1 = C2C3 = C(C(=C1O)O)OC(=O)C4 = CC(=C(C(=C43)OC2 = O)O)O",
    "AFSDNFLWKVMVRB - UHFFFAOYSA - N",
    "5.127, 11.784, 11.784, 5.127	",
    "302.194",
    "1.2774",
    "- 3.286",
    "8",
    "4",
    "186.92",
    "- 1.5983",
  ],
  [
    "11",
    "boswellic acid",
    "C[C@@H]1CC[C@@]2(CC[C@@]3(C(=CC)C",
    "HMMGKOVEOFBCAU - OQQDVLCCSA - N",
    "4.12",
    "512.728",
    "5.7783",
    "- 6.173",
    "5	",
    "1",
    "375.52",
    "- 1.7193",
  ],
  [
    "12",
    "ketoboswellic acid	",
    "C[C@@H]1CC[C@@]2(CC[C@@]3(C",
    "HMMGKOVEOFBCAU - OQQDVLCCSA - N",
    "4.12",
    "512.728",
    "5.7783",
    "- 6.173",
    "5",
    "1",
    "375.52",
    "- 1.7193",
  ],
  [
    "13",
    "ergosterol peroxide",
    "C[C@H](/C=C/[C@H](C)C(C)C)[C@H]1CC[C@@H]C",
    "VXOZCESVZIRHCJ - UFDCOOLNSA - N",
    "14.318",
    "428.654",
    "6.3859",
    "- 5.989",
    "3",
    "1",
    "324.37",
    "- 2.4641",
  ],
  [
    "14",
    "Dehydroandrographolide",
    "C[C@@]12CC[C@H]([C@@]([C@H]1CCC",
    "YIIRVUDGRKEWBV - VYMYIBDJSA - N",
    "14.475, 16.410",
    "332.438",
    "2.4676",
    "- 3.576",
    "4",
    "2",
    "252.81",
    "- 5.1251",
  ],
  [
    "15",
    "chrysin",
    "C1 = CC = C(C = C1)C2 = CC(=O)C3 = C(C = C(C = C3O2)O)O",
    "RTIXKCRFFJGDFG - UHFFFAOYSA - N",
    "7.137, 11.872",
    "254.24",
    "2.6814",
    "- 3.152",
    "4",
    "2",
    "184.68",
    "0.28194",
  ],
  [
    "16",
    "Glycyrrhetic acid",
    "C[C@]12CC[C@](C[C@H]1C3 = CC(=O)[C@@H]4[C@",
    "MPDGHEJMBKOTSU - LBWPLNRGSA - N",
    "14.584, 4.519",
    "470.691",
    "5.3559",
    "- 5.78",
    "4",
    "2",
    "341.03",
    "- 2.3558"
  ],
  [
    "17",
    "andrographolide",
    "C[C@@]12CC[C@H]([C@@]([C@H]",
    "BOJKULTULYSRAS - ODQAOENWSA - N",
    "12.582, 14.475, 16.410",
    "350.453",
    "1.883",
    "- 2.953",
    "5",
    "3",
    "258.92",
    "- 4.5926"


  ],
  [
    "18",
    "4-methylumbelliferone",
    "CC1 = CC(=O)OC2 = C1C = CC(=C2)O",
    "HSHNITRMYYLLCV - UHFFFAOYSA - N",
    "8.249",
    "176.171",
    "1.2299",
    "- 1.803",
    "3",
    "1",
    "130.83",
    "- 7.1335",
  ],
  [
    "19",
    "glycyrrhizin",
    "C[C@]12CC[C@](C[C@H]1C3 = CC)O)O)O)C)(C)C(=O)O",
    "LPLVUJXQOOQHMX - PRWQXZRYSA - N",
    "4.519, 13.060, 3.150, 17.646, 17.367, 13.408, 2.927, 19.211",
    "822.938",
    "0.9825",
    "- 5.144",
    "16",
    "8",
    "552.63",
    "- 4.2912",

  ],
  [
    "20",
    "quinine sulphate",
    "COC1 = CC2 = C(C = CN = C2S(=O)(=O)O",
    "HIDQOSJGNGSIKU - VGAHNMGYSA - N",
    "13.645, 8.313, 13.645, 8.313",
    "746.923",
    "2.6104",
    "- 3.097",
    "4",
    "1",
    "248.11",
    "1.0933"
  ],
  [
    "21",
    "11 keto boswellic acid",
    "CC1C(C(C(C(O1)OC2C(C(COC)(=O)[O -])(O1)CO)O)OC)O)O.[Na +]",
    "KXDQPKMJSMCBEY - UHFFFAOYSA - M",
    "12.663, 17.511, 13.622, 13.041, 14.740, 17.410, 14.534, 12.337, 15.430, 13.425, 16.350",
    "1221.3",
    "- 3.8184",
    "- 3.46",
    "27",
    "12",
    "780.31",
    "- 5.4715",
  ],
  [
    "22",
    "beta-caryophyllene oxide",
    "C[C@@]12CC[C@@H]3[C@H](CC3(C)C)C(=C)CC[C@H]1O2",
    "NVEQFIOZRFFVFW - GUIRCDHDSA - N",
    "N / A",
    "220.355",
    "4.0553",
    "- 3.558",
    "1",
    "0",
    "177.3",
    "- 4.768",


  ],
  [
    "23",
    "caffeine",
    "CN1C = NC2 = C1C(=O)N(C(=O)N2C)C",
    "RYYVLZVUVIJVGH - UHFFFAOYSA - N",
    "N / A",
    "194.193",
    "- 0.1784",
    "- 1.144",
    "6",
    "0",
    "140.6",
    "2.5858",
  ],
  [
    "24",
    "catechin",
    "C1[C@@H]([C@H](OC2 = CC(=CC(=C21)O)O)C3 = CC(=C(C = C3)O)O)O",
    "PFTAWBLQPZVEMU - UKRRQHHQSA - N",
    "16.167, 13.877, 9.311, 8.744, 14.866",
    "290.27",
    "1.5087",
    "- 1.764",
    "6",
    "5",
    "200.03",
    "0.31525",
  ],
  [
    "25",
    "piperic acid",
    "C1OC2 = C(O1)C = C(C = C2) / C=C / C=C / C(=O)O",
    "RHBGITBPARBDPH - UHFFFAOYSA - N",
    "4.166",
    "218.207",
    "2.2419",
    "- 3.022",
    "4",
    "1",
    "170.62",
    "0.40767",
  ],
  [
    "26",
    "curcumin",
    "COC1 = C(C = CC(=C1) / C=C / C(=O)CC(=O) / C=C / C2=CC(=C(C = C2)O)OC)O",
    "VFLDPWHFBUODDF - UHFFFAOYSA - N",
    "8.863, 8.863",
    "368.384",
    "2.949",
    "- 3.622",
    "6",
    "2",
    "292.5",
    "- 4.7745",
  ],
  [
    "27",
    "chalcone",
    "C1 = CC = C(C = C1) / C=C / C(=O)C2 = CC = CC = C2",
    "DQFBYFPFKXHELB - UHFFFAOYSA - N",
    "N / A",
    "208.259",
    "3.3038",
    "- 3.84",
    "1",
    "0",
    "177.27",
    "0.1125",
  ],
  [
    "28",
    "1-EICOSANOL",
    "CCCCCCCCCCCCCCCCCCCCO",
    "BTFJIXJJCSYFAL - UHFFFAOYSA - N",
    "14.832",
    "298.552",
    "8.2297",
    "- 5.337",
    "1",
    "1",
    "293.55",
    "- 32.166",
  ],
  [
    "29",
    "3-demethyl colchicine",
    "CC(=O)N[C@H]1CCC2 = CC(=C(C(=C2C3 = CC = C(C(=O)C = C13)OC)OC)OC)O",
    "",
    "384.407",
    "1.6914",
    "- 3.696",
    "7",
    "1",
    "289.66",
    "1.024",
    ""
  ],
  [
    "30",
    "3-demethyl N-formyl-N-deacetylcolchicine",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "31",
    "Colchicine",
    "CC(=O)N[C@H]1CCC2 = CC(=C(C(=C2C3 = CC = C(C(=O)C = C13)OC)OC)OC)OC",
    "",
    "398.434",
    "2.1439",
    "- 3.293",
    "7",
    "1",
    "303.42",
    "1.0433",
    "",
  ],
  [
    "32",
    "Gloriosine",
    "COC1 = CC = C2C(=CC1 = O)[C@H](CCC3 = CC(=C(C(=C32)OC)OC)OC)NC = O",
    "",
    "385.415",
    "1.6756",
    "- 3.165",
    "7",
    "1",
    "298.2",
    "1.3115",
  ],
  [
    "33",
    "6-methoxy salicylic acid",
    "COC1 = CC(=C(C = C1)O)C(=O)O",
    "",
    "1",
    "67.14",
    "0.8039",
    "- 1.457",
    "4",
    "1",
    "122.87",
    "- 1.623",
  ],
  [
    "34",
    "N-Deacetyl-N-formyl-lumicolchicine",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "35",
    "b-Lumicolchicine",
    "CC(=O)NC1CCC2 = CC(=C(C(=C2C3 = C1C4C3C = C(C4 = O)OC)OC)OC)OC",
    "",
    "399.442",
    "1.6998",
    "- 3.14",
    "7",
    "1",
    "293.67",
    "0.71003",
  ],
  [
    "36",
    "y-Lumicolchicine",
    "CC(=O)NC1CCC2 = CC(=C(C(=C)OC",
    "",
    "398.434",
    "1.9807",
    "- 3.387",
    "7",
    "1",
    "288.42",
    "0.72959",
  ],
  [
    "37",
    "Colchicoside",
    "CC(=O)N[C@H]1CCC2 = CC(=C(C(=C2C3 = CC =)CO)O)O)O",
    "",
    "546.547",
    "- 0.3271",
    "- 2.724",
    "12",
    "4",
    "391.47",
    "0.35434"
  ],
  [
    "38",
    "2-demethyl-b-lumicolchicine",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "39",
    "pN-Deacetyl-N-formyl-cornigerine (new compound)",
    "CC(=O)NC1CCC2 = CC3 = C(C(=C2C4 = CC = C(C(=O)C = C14)OC)OC)OCO3",
    "383.399",
    "2.1144",
    "- 3.721",
    "7",
    "1",
    "284.41",
    "1.0442",
  ],
  [
    "40",
    "3-demethyl-?-lumicolchicine",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "41",
    "3-Demethyl-N-deacetyl-N-formyl-?-lumicolchicine",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "42",
    "Bergenin",
    "COC1 = C(C = C2C(=C1O)[C]CO)O)O) OC2 = O) O",
    "YWJXCIXBAKGUKZ - FQVYEVNKSA - N",
    "328.272",
    "- 1.626",
    "- 0.949",
    "9",
    "5",
    "214.28",
    "- 1.6415",
  ],
  [
    "43",
    "Gibberellic acid",
    "C[C@@]12[C@=C)C5)O) C(=O)O) OC2 = O) O",
    "IXORZMNAPKEEDV - MYSPZSBCSA - N",
    "346.378",
    "0.0924",
    "- 2.659",
    "6",
    "3",
    "218.74",
    "- 1.7675",
  ],
  [
    "44",
    "Pongamol",
    "CC(C)(C = C)C(C(3 = C(C = C2)OC = C3)OC",
    "FECOWIAOIRMVIE - IBGZPJMESA - N",
    "362.424",
    "4.6461",
    "- 6.039",
    "4",
    "0",
    "287.04",
    "- 5.0387",
  ],
  [
    "45",
    "Pongol",
    "COC1 = CC = CC(=C1)C2 = CC(=O)C3 = C(O2)C4 = C(C = C3)OC = C4",
    "OHKLPDQPGIVELF - UHFFFAOYSA - N",
    "292.289",
    "3.7544",
    "- 4.921",
    "4",
    "0",
    "218.53",
    "0.025945",
  ],
  [
    "46",
    "Quercetin",
    "C1 = CC(=C(CO)O)O) O",
    "REFJWTPEDVJJIY - UHFFFAOYSA - N",
    "302.237",
    "1.4902",
    "- 2.491",
    "7",
    "5",
    "201.94",
    "- 0.082832",
  ],
  [
    "47",
    "Lupeol",
    "CC(=C)[C@@H]1CC[C@]2([C@H]1[C@H(C) C)O)C) C",
    "MQYXUWHLBZFQQO - DCTTWMPASA - N",
    "426.726",
    "7.6469",
    "- 6.803",
    "1",
    "1",
    "325.57",
    "- 22.172",
  ],
  [
    "48",
    "Rutin",
    "C[C@H]1[C@@H]([C@H]([C@H]([C = C5)O)O)O)O)O)O)O) O",
    "IKGXIBQEEMLURG - RZIXAHTPSA - N",
    "610.519",
    "- 1.2573",
    "- 2.398",
    "16",
    "10",
    "397.71",
    "1.9337",
  ],
  [
    "49",
    "Ferulic acid",
    "COC1 = C(C = CC(=C1) / C=C / C(=O)O)O",
    "KSEBMYQBYZTDHS - UHFFFAOYSA - N",
    "194.185",
    "1.0582",
    "- 1.721",
    "4",
    "2",
    "152.47",
    "0.27506",
  ],
  [
    "50",
    "Gallic acid",
    "C1 = C(C = C(C(=C1O)O)O)C(=O)O",
    "",
    "169.112",
    "0.1825",
    "- 0.847",
    "5",
    "3",
    "113.31",
    "- 1.8434",
  ],


];